LangString addOrReinstall ${LANG_ARABIC} "إضافة المكونات أو إعادة تثبيتها"
LangString alreadyInstalled ${LANG_ARABIC} "مثبت مسبقًا"
LangString alreadyInstalledLong ${LANG_ARABIC} "${PRODUCTNAME} ${VERSION} مثبت مسبقًا. اختر العملية المطلوبة ثم اضغط التالي."
LangString appRunning ${LANG_ARABIC} "{{product_name}} قيد التشغيل. أغلقه أولًا ثم أعد المحاولة."
LangString appRunningOkKill ${LANG_ARABIC} "{{product_name}} قيد التشغيل.$\nاضغط موافق لإغلاقه"
LangString chooseMaintenanceOption ${LANG_ARABIC} "اختر عملية الصيانة المطلوبة."
LangString choowHowToInstall ${LANG_ARABIC} "اختر طريقة تثبيت ${PRODUCTNAME}."
LangString createDesktop ${LANG_ARABIC} "إنشاء اختصار على سطح المكتب"
LangString dontUninstall ${LANG_ARABIC} "عدم إزالة التثبيت"
LangString dontUninstallDowngrade ${LANG_ARABIC} "عدم إزالة التثبيت"
LangString failedToKillApp ${LANG_ARABIC} "تعذر إغلاق {{product_name}}. أغلقه يدويًا ثم أعد المحاولة."
LangString installingWebview2 ${LANG_ARABIC} "جارٍ تثبيت WebView2..."
LangString newerVersionInstalled ${LANG_ARABIC} "يوجد إصدار أحدث من ${PRODUCTNAME} مثبت بالفعل."
LangString older ${LANG_ARABIC} "أقدم"
LangString olderOrUnknownVersionInstalled ${LANG_ARABIC} "يوجد إصدار آخر من ${PRODUCTNAME} مثبت على الجهاز. يفضّل إزالة الإصدار الحالي قبل المتابعة."
LangString silentDowngrades ${LANG_ARABIC} "لا يمكن تثبيت إصدار أقدم تلقائيًا.$\n"
LangString unableToUninstall ${LANG_ARABIC} "تعذر إزالة التثبيت."
LangString uninstallApp ${LANG_ARABIC} "إزالة ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ARABIC} "إزالة الإصدار الحالي قبل التثبيت"
LangString unknown ${LANG_ARABIC} "غير معروف"
LangString webview2AbortError ${LANG_ARABIC} "تعذر تثبيت WebView2. أعد تشغيل المثبت وحاول مرة أخرى."
LangString webview2DownloadError ${LANG_ARABIC} "تعذر تنزيل WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_ARABIC} "تم تنزيل WebView2 بنجاح"
LangString webview2Downloading ${LANG_ARABIC} "جارٍ تنزيل WebView2..."
LangString webview2InstallError ${LANG_ARABIC} "فشل تثبيت WebView2 برمز الخطأ $1"
LangString webview2InstallSuccess ${LANG_ARABIC} "تم تثبيت WebView2 بنجاح"
LangString deleteAppData ${LANG_ARABIC} "حذف بيانات التطبيق"
