use serde::Serialize;
use std::{path::PathBuf,process::{Command,Output}};
use tauri::{AppHandle,Manager};
use thiserror::Error;
#[derive(Debug,Error)] pub enum AndroidError{#[error("ADB is not available. Bundle platform-tools with H TRANS or set HTRANS_ADB.")] AdbUnavailable,#[error("ADB command failed: {0}")] CommandFailed(String)}
#[derive(Debug,Clone,Serialize)] #[serde(rename_all="camelCase")] pub struct AndroidDevice{pub serial:String,pub state:String,pub manufacturer:String,pub model:String,pub android_version:String,pub battery_level:Option<u8>,pub storage_summary:Option<String>,pub whatsapp_installed:bool,pub whatsapp_business_installed:bool}
pub fn adb_path(app:&AppHandle)->PathBuf{if let Ok(c)=std::env::var("HTRANS_ADB"){return PathBuf::from(c)} if let Ok(r)=app.path().resource_dir(){let p=r.join("platform-tools").join("adb.exe");if p.exists(){return p}} PathBuf::from("adb")}
pub fn adb(app:&AppHandle,args:&[&str])->Result<Output,AndroidError>{let out=Command::new(adb_path(app)).args(args).output().map_err(|_|AndroidError::AdbUnavailable)?;if out.status.success(){Ok(out)}else{Err(AndroidError::CommandFailed(String::from_utf8_lossy(&out.stderr).trim().into()))}}
fn text(app:&AppHandle,s:&str,args:&[&str])->Result<String,AndroidError>{let mut a=vec!["-s",s];a.extend_from_slice(args);Ok(String::from_utf8_lossy(&adb(app,&a)?.stdout).trim().into())}
pub fn detect_device(app:&AppHandle)->Result<Option<AndroidDevice>,AndroidError>{let out=adb(app,&["devices"])?;let stdout=String::from_utf8_lossy(&out.stdout);let mut selected=None;for line in stdout.lines().skip(1){let mut p=line.split_whitespace();if let (Some(s),Some(st))=(p.next(),p.next()){selected=Some((s.to_string(),st.to_string()));if st=="device"{break}}}let Some((serial,raw))=selected else{return Ok(None)};if raw!="device"{let state=if raw=="unauthorized"{"unauthorized"}else{"offline"};return Ok(Some(AndroidDevice{serial,state:state.into(),manufacturer:String::new(),model:String::new(),android_version:String::new(),battery_level:None,storage_summary:None,whatsapp_installed:false,whatsapp_business_installed:false}))}let manufacturer=text(app,&serial,&["shell","getprop","ro.product.manufacturer"]).unwrap_or_default();let model=text(app,&serial,&["shell","getprop","ro.product.model"]).unwrap_or_default();let android_version=text(app,&serial,&["shell","getprop","ro.build.version.release"]).unwrap_or_default();let bd=text(app,&serial,&["shell","dumpsys","battery"]).unwrap_or_default();let battery_level=bd.lines().find_map(|l|l.trim().strip_prefix("level:")).and_then(|v|v.trim().parse().ok());let storage=text(app,&serial,&["shell","df","-h","/sdcard"]).unwrap_or_default();let storage_summary=storage.lines().last().map(|l|{let c:Vec<&str>=l.split_whitespace().collect();if c.len()>=5{format!("{} used / {} total",c[2],c[1])}else{l.to_string()}});let pk=text(app,&serial,&["shell","pm","list","packages"]).unwrap_or_default();Ok(Some(AndroidDevice{serial,state:"connected".into(),manufacturer,model,android_version,battery_level,storage_summary,whatsapp_installed:pk.contains("package:com.whatsapp"),whatsapp_business_installed:pk.contains("package:com.whatsapp.w4b")}))}
