use crate::android;
use serde::{Deserialize,Serialize};use sha2::{Digest,Sha256};use std::{fs::{self,File},io::{Read,Write},path::{Path,PathBuf},time::{SystemTime,UNIX_EPOCH}};use tauri::{AppHandle,Emitter};use tempfile::tempdir;use thiserror::Error;use zip::{write::SimpleFileOptions,ZipArchive,ZipWriter};
#[derive(Debug,Error)] pub enum WError{#[error("No authorized Android device is connected.")] NoDevice,#[error("Unsupported WhatsApp variant: {0}")] Variant(String),#[error("No local WhatsApp database folder was found on the phone.")] Missing,#[error("Backup contains no WhatsApp chat database files.")] Empty,#[error("Invalid or damaged H TRANS backup: {0}")] Invalid(String),#[error(transparent)] Io(#[from]std::io::Error),#[error(transparent)] Zip(#[from]zip::result::ZipError),#[error("ADB error: {0}")] Adb(String),#[error("Metadata error: {0}")] Meta(String)}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct Progress{operation:&'static str,percent:u8,stage:String,detail:Option<String>}
#[derive(Serialize,Deserialize)]struct Manifest{format:String,version:u32,created_unix:u64,variant:String,package:String,source_serial:String,media_included:bool,database_files:Vec<MFile>}
#[derive(Serialize,Deserialize)]struct MFile{name:String,sha256:String,bytes:u64}
struct V{package:&'static str,dir:&'static str}
fn vi(v:&str)->Result<V,WError>{match v{"personal"=>Ok(V{package:"com.whatsapp",dir:"/sdcard/Android/media/com.whatsapp/WhatsApp/Databases"}),"business"=>Ok(V{package:"com.whatsapp.w4b",dir:"/sdcard/Android/media/com.whatsapp.w4b/WhatsApp Business/Databases"}),x=>Err(WError::Variant(x.into()))}}
fn emit(app:&AppHandle,op:&'static str,p:u8,s:&str,d:Option<String>){let _=app.emit("transfer-progress",Progress{operation:op,percent:p,stage:s.into(),detail:d});}
fn serial(app:&AppHandle)->Result<String,WError>{android::detect_device(app).map_err(|e|WError::Adb(e.to_string()))?.filter(|d|d.state=="connected").map(|d|d.serial).ok_or(WError::NoDevice)}
fn hash(p:&Path)->Result<String,WError>{let mut f=File::open(p)?;let mut h=Sha256::new();let mut b=[0u8;131072];loop{let n=f.read(&mut b)?;if n==0{break}h.update(&b[..n]);}Ok(format!("{:x}",h.finalize()))}
fn dbs(root:&Path)->Result<Vec<PathBuf>,WError>{let mut v=vec![];if !root.exists(){return Ok(v)}for e in fs::read_dir(root)?{let p=e?.path();if p.is_file(){let n=p.file_name().and_then(|x|x.to_str()).unwrap_or("");if n.starts_with("msgstore")&&n.contains(".crypt"){v.push(p)}}}v.sort();Ok(v)}
pub fn backup(app:&AppHandle,variant:&str,dest:&str)->Result<String,WError>{let info=vi(variant)?;let s=serial(app)?;emit(app,"backup",3,"Checking device",Some(s.clone()));let t=tempdir()?;let pulled=t.path().join("Databases");fs::create_dir_all(&pulled)?;emit(app,"backup",12,"Reading local WhatsApp backup",Some("Media is excluded".into()));let local=pulled.to_string_lossy().to_string();android::adb(app,&["-s",&s,"pull",info.dir,&local]).map_err(|e|WError::Adb(e.to_string()))?;let mut files=dbs(&pulled)?;if files.is_empty(){files=dbs(&pulled.join("Databases"))?}if files.is_empty(){return Err(WError::Empty)}package(app,variant,info.package,&s,files,dest)}
fn package(app:&AppHandle,variant:&str,package:&str,s:&str,files:Vec<PathBuf>,dest:&str)->Result<String,WError>{emit(app,"backup",62,"Creating H TRANS backup",None);let mut mf=vec![];for f in &files{mf.push(MFile{name:f.file_name().unwrap().to_string_lossy().into(),sha256:hash(f)?,bytes:fs::metadata(f)?.len()})}let m=Manifest{format:"H-TRANS-WHATSAPP".into(),version:1,created_unix:SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs(),variant:variant.into(),package:package.into(),source_serial:s.into(),media_included:false,database_files:mf};let target=PathBuf::from(dest);if let Some(p)=target.parent(){fs::create_dir_all(p)?}let mut z=ZipWriter::new(File::create(&target)?);let o=SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);z.start_file("manifest.json",o)?;z.write_all(&serde_json::to_vec_pretty(&m).map_err(|e|WError::Meta(e.to_string()))?)?;for (i,f) in files.iter().enumerate(){let n=f.file_name().unwrap().to_string_lossy();z.start_file(format!("databases/{n}"),o)?;let mut input=File::open(f)?;std::io::copy(&mut input,&mut z)?;emit(app,"backup",70+(((i+1)as f32/files.len()as f32)*22.0)as u8,"Packing chat database",Some(n.into()));}z.finish()?;emit(app,"backup",95,"Verifying backup",None);verify(&target)?;emit(app,"backup",100,"Backup complete",Some(target.display().to_string()));Ok(target.display().to_string())}
fn verify(p:&Path)->Result<Manifest,WError>{let mut a=ZipArchive::new(File::open(p)?)?;let m:Manifest={let mut e=a.by_name("manifest.json").map_err(|_|WError::Invalid("manifest.json missing".into()))?;let mut j=String::new();e.read_to_string(&mut j)?;serde_json::from_str(&j).map_err(|e|WError::Invalid(e.to_string()))?};if m.format!="H-TRANS-WHATSAPP"||m.version!=1||m.media_included||m.database_files.is_empty(){return Err(WError::Invalid("unsupported backup format".into()))}Ok(m)}
pub fn restore(app:&AppHandle,file:&str,variant:&str)->Result<(),WError>{let info=vi(variant)?;let s=serial(app)?;let src=PathBuf::from(file);emit(app,"restore",3,"Validating H TRANS backup",None);let m=verify(&src)?;if m.variant!=variant{return Err(WError::Invalid(format!("backup is for {}",m.variant)))}let _=android::adb(app,&["-s",&s,"shell","am","force-stop",info.package]);let t=tempdir()?;let mut a=ZipArchive::new(File::open(&src)?)?;emit(app,"restore",15,"Extracting chat databases",None);for x in &m.database_files{let mut z=a.by_name(&format!("databases/{}",x.name)).map_err(|_|WError::Invalid(format!("missing {}",x.name)))?;let p=t.path().join(&x.name);let mut o=File::create(&p)?;std::io::copy(&mut z,&mut o)?;if hash(&p)?!=x.sha256{return Err(WError::Invalid(format!("checksum mismatch for {}",x.name)))}}android::adb(app,&["-s",&s,"shell","mkdir","-p",info.dir]).map_err(|e|WError::Adb(e.to_string()))?;for (i,x) in m.database_files.iter().enumerate(){let p=t.path().join(&x.name).to_string_lossy().to_string();let r=format!("{}/{}",info.dir,x.name);emit(app,"restore",45+((i as f32/m.database_files.len()as f32)*45.0)as u8,"Restoring chat database",Some(x.name.clone()));android::adb(app,&["-s",&s,"push",&p,&r]).map_err(|e|WError::Adb(e.to_string()))?;}emit(app,"restore",100,"Restore files ready",Some("Complete WhatsApp setup and choose the local backup when prompted.".into()));Ok(())}
