import {useEffect,useMemo,useState} from 'react';
import {open,save} from '@tauri-apps/plugin-dialog';
import {ArchiveRestore,HardDriveDownload,RefreshCw,ShieldCheck,Smartphone,WifiOff} from 'lucide-react';
import {backend} from './lib/backend';
import type {AndroidDevice,TransferProgress,WhatsAppVariant} from './types';

const idle:TransferProgress={operation:'backup',percent:0,stage:'Ready'};
export default function App(){
 const [device,setDevice]=useState<AndroidDevice|null>(null); const [variant,setVariant]=useState<WhatsAppVariant>('personal'); const [progress,setProgress]=useState(idle); const [running,setRunning]=useState(false); const [result,setResult]=useState('');
 const refresh=async()=>{try{setDevice(await backend.detectDevice())}catch{setDevice(null)}};
 useEffect(()=>{refresh();const t=window.setInterval(refresh,3000);let u:(()=>void)|undefined;backend.onProgress(setProgress).then(fn=>u=fn);return()=>{window.clearInterval(t);u?.();}},[]);
 const connected=device?.state==='connected'; const supported=useMemo(()=>device&&(variant==='personal'?device.whatsappInstalled:device.whatsappBusinessInstalled),[device,variant]);
 async function doBackup(){const dest=await save({title:'Save H TRANS backup',defaultPath:`H-TRANS_${device?.model||'Android'}_${variant}.htrans`,filters:[{name:'H TRANS Backup',extensions:['htrans']}]});if(!dest)return;setRunning(true);setResult('');try{setResult(`Saved: ${await backend.backupWhatsApp(variant,dest)}`)}catch(e){setResult(`Backup failed: ${String(e)}`)}finally{setRunning(false)}}
 async function doRestore(){const f=await open({title:'Select H TRANS backup',multiple:false,filters:[{name:'H TRANS Backup',extensions:['htrans']}]});if(!f||Array.isArray(f))return;setRunning(true);setResult('');try{await backend.restoreWhatsApp(f,variant);setResult('Restore files transferred. Complete WhatsApp setup and choose the local backup when prompted.')}catch(e){setResult(`Restore failed: ${String(e)}`)}finally{setRunning(false)}}
 return <main className="shell"><header><div className="brand"><img src="/src/assets/h-trans-icon.svg"/><div><strong>H TRANS</strong><span>Your chats. Your PC.</span></div></div><button className="ghost" onClick={refresh}><RefreshCw size={17}/>Refresh</button></header><section className="grid"><article className="panel device"><div className="heading"><div><p className="eyebrow">CONNECTED DEVICE</p><h1>{connected?'Android phone detected':'Connect your Android phone'}</h1></div><span className={connected?'status on':'status'}>{connected?'Connected':device?.state||'Waiting'}</span></div><div className="stage"><div className="phone"><div className="screen">{connected?<><Smartphone size={48}/><strong>{device?.model}</strong><span>{device?.manufacturer}</span><small>Android {device?.androidVersion}</small></>:<><WifiOff size={46}/><strong>No phone connected</strong><small>Connect USB and allow debugging.</small></>}</div></div><div className="facts"><Fact l="Serial" v={device?.serial||'—'}/><Fact l="Battery" v={device?.batteryLevel!=null?`${device.batteryLevel}%`:'—'}/><Fact l="Storage" v={device?.storageSummary||'—'}/><Fact l="Media" v="Excluded"/></div></div></article><article className="panel actions"><p className="eyebrow">SELECT DATA</p><h2>WhatsApp chats</h2><p className="muted">Chats only. Photos, videos, audio and documents are never included.</p><div className="choices"><Choice active={variant==='personal'} title="WhatsApp" sub={device?.whatsappInstalled?'Detected':'Not detected'} onClick={()=>setVariant('personal')}/><Choice active={variant==='business'} title="WhatsApp Business" sub={device?.whatsappBusinessInstalled?'Detected':'Not detected'} onClick={()=>setVariant('business')}/></div><div className="privacy"><ShieldCheck size={20}/>100% local. No chat data is uploaded.</div><div className="buttons"><button className="primary" disabled={!connected||!supported||running} onClick={doBackup}><HardDriveDownload size={19}/>Backup</button><button className="secondary" disabled={!connected||!supported||running} onClick={doRestore}><ArchiveRestore size={19}/>Restore</button></div><div className="progress"><div><span>{progress.stage}</span><strong>{progress.percent}%</strong></div><div className="track"><i style={{width:`${progress.percent}%`}}/></div><small>{progress.detail||(running?'Do not disconnect your phone.':'Ready.')}</small></div>{result&&<p className="result">{result}</p>}</article></section></main>}
function Fact({l,v}:{l:string;v:string}){return <div className="fact"><span>{l}</span><strong>{v}</strong></div>}
function Choice({active,title,sub,onClick}:{active:boolean;title:string;sub:string;onClick:()=>void}){return <button className={active?'choice active':'choice'} onClick={onClick}><b>{active?'✓':''}</b><span><strong>{title}</strong><small>{sub}</small></span></button>}
